### ISSUE TITLE
arena创建2MB文件的问题

### ISSUE THREAD

**Issue by cwk08** [ISCS-ZJU/NVAlloc#1]
作者您好，我在运行NVAlloc代码时发现随着分配操作进行，arena会创建大量2MB的文件，这些文件的用途是什么？当数据规模的增大，大量的2MB文件达到了系统允许的创建上限，后续的分配无法继续进行了（在example.cpp中大约1000万左右的分配请求之后就会出错），请问当前的NVAlloc设计是否可以解决这个问题？

**Comment by dangzzz** [comment]
The 2 MB files are heap files. 

The issue you encountered can be addressed by: 
(1) Modify the default size of heap files to allocate fewer heap files; 
(2) Change your filesystem to one that supports a higher number of files under one directory;
(3) Add more filesystem paths for allocating heap files in the source code.

Hope it helps you.

**Comment by cwk08** [comment]
Thanks for reply, change the heap size seems to be an easy way.
